apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: s06v9m9hs-python-gitops
  description: This is GitOps manifest for s06v9m9hs-python   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: tssc/gitops=s06v9m9hs-python
    backstage.io/kubernetes-id: s06v9m9hs-python 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: s06v9m9hs-python
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:s06v9m9hs-python
