apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: s06v9m9hs-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: s06v9m9hs-python 
  name: s06v9m9hs-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: s06v9m9hs-python 
